name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels: ["breaking"]
  minor:
    labels: ["enhancement"]
  patch:
    labels: ["bug", "documentation"]
  default: patch
categories:
  - title: "Breaking changes"
    labels: ["breaking"]
  - title: "New features"
    labels: ["enhancement"]
  - title: "Bug fixes"
    labels: ["bug"]
  - title: "Documentation"
    labels: ["documentation"]
  - title: "Maintenance"
    labels: ["chore", "dependencies"]
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
exclude-labels: ["skip-changelog"]
